language: go
dist: trusty

sudo: required

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install libcairo2-dev -y

script: make all test vet

matrix:
  include:
    - go: 1.9.x
    - go: 1.10.x
    - go: 1.11.x
    - go: master
